### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by MaceWindu**

### CODE REVIEW

**Review by viceroypenguin — APPROVED** [review]

**Comment by MaceWindu** [comment]
Not so fast...
Also makes sense to fix build warnings https://dev.azure.com/linq2db/linq2db/_build/results?buildId=8824&view=results

image

image

**Comment by MaceWindu** [comment]
to reproduce, enable procedures generation

**Comment by viceroypenguin** [comment]
Will check the procedures.

The package source issue is pre-existing. The relationship is intentional, to generate based on existing DC code (even if l2db doesn't generate sql based on it, we want to respect previously used code).

**Comment by viceroypenguin** [comment]
Will revisit tomorrow - earlier, was defaulting to System.Data.SqlClient for mssql, but now it is defaulting to the 4.0 default of Microsoft.Data.SqlClient, which is not present to be loaded.

**Comment by MaceWindu** [comment]
Some t4 changes since last release should be migrated. Check those diffs (see changes to ttinclude files only):

Procedures refactoring for v4:
https://github.com/linq2db/linq2db/commit/fcdb45ef06d963bde72a66ab30bdad4463031bc5#diff-fef8bdc780a81be82c1d4afe34e4396bf8d7f37c1a8f995b7bd48f67770e96b3

This one probably not apply to linqpad code:
https://github.com/linq2db/linq2db/commit/59d6bb2d5d2435731a1a15ca9e3e084eca312134#diff-fef8bdc780a81be82c1d4afe34e4396bf8d7f37c1a8f995b7bd48f67770e96b3

Maybe this:
https://github.com/linq2db/linq2db/commit/1fd69cc760826b882b5c79f7c4d023624fe07e1f#diff-fef8bdc780a81be82c1d4afe34e4396bf8d7f37c1a8f995b7bd48f67770e96b3

Maybe this:
https://github.com/linq2db/linq2db/commit/75cda68006ffa1d4d0c04c5c39233fe345658a3c#diff-df6fd105f28c0d8a80504bda8f8957f0fe0a88411ac911e1a9705eef875818b9

Rename (casing) of some classes (if applicable to linqpad):
https://github.com/linq2db/linq2db/commit/459fb64b639cfa343f3f301229c997e83e978ad0#diff-fef8bdc780a81be82c1d4afe34e4396bf8d7f37c1a8f995b7bd48f67770e96b3

SystemType became nullable (other changes probably not important):
https://github.com/linq2db/linq2db/commit/e1dadf1eca938e4b68450636864bcf78a2f3fc43

Type length changed from long to int:
https://github.com/linq2db/linq2db/commit/185021b36beddaa19027482926098c4914995143

Packages support:
https://github.com/linq2db/linq2db/commit/908cdb3973f8cde442d39453edd99bdd21a1e5d1

**Pull request merged**
