### PR TITLE
Re-enable DB2 for iSeries support

### PR DESCRIPTION
**Pull request by mhellsten**
Re-enabling support for DB2 for iSeries via the Linq2DB4iSeries package

### CODE REVIEW

**Review by viceroypenguin — APPROVED** [review]
@mhellsten if you can provide some confirmation that iSeries is working as expected (a screenshot or something?), then lgtm. Thank you!

**Comment by MaceWindu** [comment]
@viceroypenguin check discussion here https://github.com/linq2db/linq2db.LINQPad/issues/118

Will release tomorrow or on saturday

**Comment by viceroypenguin** [comment]
> @viceroypenguin check discussion here #118
> 
> Will release tomorrow or on saturday

Yes, I read this. I did not see any proof from @mhellsten of working status there or here. Some confirmation before merging would be helpful.

**Comment by viceroypenguin** [comment]
Yup, I'm satisfied! Thank you!

**Review by MaceWindu — APPROVED** [review]

**Pull request merged**
